language: cpp
compiler: gcc

before_install:cmake:
  - sudo apt-get install xorg-dev libglu1-mesa-dev libxi-dev libxrandr-dev
  - sudo apt-get install x11proto-xf86vidmode-dev

install: true

before_script:
  - mkdir build
  - cd build
  - cmake -DFENSTERCHEN_TESTS=TRUE ..
  - make -j2

script:
  - make test
